### ISSUE TITLE
Support more platforms

### ISSUE THREAD

**Issue by MrIvanPlays** [ArcanePlugins/Treasury#225]
- [x] Sponge Support
- [x] Minestom Support

**Comment by lokka30** [comment]
Is it worth delaying 2.0 for platform support?

Advantage: We are able to revise the API to support those platforms if required, instead of having to either abandon the idea of supporting that platform, make an unfavourable workaround, or embarrassingly break the API again. 

Disadvantage: v2 is delayed considerably longer than hoped.

What do you think? 🙂

**Comment by MrIvanPlays** [comment]
yes it is worth
